name: jsn

services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Containerfile
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/nginx/ssl:ro
      - ./certbot/webroot:/var/certbot:ro
    depends_on:
      - main-site
    networks:
      - internal

  main-site:
    build:
      context: ./site
      dockerfile: Containerfile
    restart: always
    expose:
      - "80"
    networks:
      - internal

  red-and-black-knights:
    build:
      context: .
      dockerfile: projects/red-and-black-knights/Containerfile
    restart: always
    expose:
      - "80"
    networks:
      - internal

  software-renderer:
    build:
      context: .
      dockerfile: projects/software-renderer/Containerfile
    restart: always
    expose:
      - "80"
    networks:
      - internal

  scavanger:
    build:
      context: ./projects/scavanger
      dockerfile: Containerfile
    restart: always
    expose:
      - "80"
    networks:
      - internal

networks:
  internal: {}
