worker_processes auto;
events { worker_connections 1024; }

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    sendfile on;
    keepalive_timeout 65;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    map $status $status_text {
        400 'Bad Request';
        401 'Unauthorized';
        403 'Forbidden';
        404 'Not Found';
        500 'Internal Server Error';
        502 'Bad Gateway';
        503 'Service Unavailable';
        504 'Gateway Timeout';
        default 'Something is wrong';
    }

    include /etc/nginx/conf.d/*.conf;
}
